### ISSUE TITLE
Set up egor to use Travis CI and/or AppVeyor?

### ISSUE THREAD

**Issue by krivit** [tilltnet/egor#1]
These services compile the packages and run `R CMD check` after every commit, which will help get the package ready for CRAN.

I can try to set it up myself, but I am not 100% sure if I can do it or if Till will have to. What do y'all think?

**Comment by krivit** [comment]
Travis CI works. AppVeyor also builds and tests on Windows, so we should probably set it up.

**Comment by tilltnet** [comment]
Ok, AppVeyor is now also set up.
