### ISSUE TITLE
subset() method for egor objects

### ISSUE THREAD

**Issue by krivit** [tilltnet/egor#2]
R has a "standard" function for filtering table-like data structures: `subset()`.

Once we've implemented a general `subset()` method, we can build on it to write other manipulations. `ergm.ego` implements a `subset()` method, but only on egos.

The following interface makes sense to me:

```
subset(x, subset.ego, subset.alter, 
          select.ego, select.alter, ...,
          dup.action=c("make.unique", "fail", "number"))
```
Here, `subset.ego` and `subset.alter` are expressions evaluated on the columns of the `ego` table and of each `alter` subtable, and similarly with `select`. The `subset.ego` expression should also "access" its alter column (`.alters`?), and, if we can manage it, the `subset.alter` expression should be able to access its ego, perhaps via a "virtual" one-row subtable `.ego`. This would allow alters to be filtered as a function of their egos, for example.

`dup.action` is used when subset (e.g., `c(1,1)`) causes rows to be duplicated to determine new ego and/or alter IDs.

If egos get filtered, `subset()` should also filter out the corresponding rows of the `ego.design` attribute.

**Edit:** The above-described interface was not what I ultimately implemented. See `?subset.egor`.

**Comment by krivit** [comment]
Since the rest of the code is independent of ego IDs (whatever they are), `dup.action` is probably not needed.

**Comment by krivit** [comment]
1. This code is thus far untested.

2. We need to figure out what to do with ties when alters are removed or duplicated. I am guessing that even if we don't need an explicit ego ID, we might need an explicit alter-within-ego ID, as well as mechanisms for when alters get duplicated: new alters and their ties will need new unique names. (And, for that matter, what *should* happen to ties when alters are duplicated?)

**Comment by raffaelevacca** [comment]
What do you mean by "duplicated" alter? Is that an alter that is duplicated in all attributes, or just the name, or other? 
In principle, I think that if two alters (within the same egoID) are the same person, we could safely keep only the first instance of that alter.

**Comment by krivit** [comment]
The issue might arise when performing index operations on alter subtables. Generally, for a table `x`,
```
x[c(1,1,2),]
```
returns a table with two copies of the first row of `x` and one of the second. Since egoIDs are effectively optional, they don't need to be unique, but if alter-alter ties are observed, alter IDs must be unique.

**Comment by krivit** [comment]
Also, I've been remiss in referencing this issue while working on `subset.egor` and `[.egor`, but it looks to be at a satisfactory point, if not exactly what I had originally envisioned. @tilltnet, @raffaelevacca please take a look.

**Comment by tilltnet** [comment]
Could you provide an example on how to filter alters or alter_ties? I can't figure it out. Ty

**Comment by krivit** [comment]
Sure. Do we have a "standard" example `egor` dataset?

**Comment by tilltnet** [comment]
I updated the example file to an egor object in 0f3d344.
data("egor32")

**Comment by krivit** [comment]
Thanks. In the meantime, I've added some usage examples in generating data in 2594f4d.

**Comment by krivit** [comment]
Another tweak in 2ee3630db.

**Comment by krivit** [comment]
>  data("egor32")

It's `egoR32`.

We should probably standardize on one capitalization and use it throughout.

**Comment by tilltnet** [comment]
> We should probably standardize on one capitalization and use it throughout.
Yes sorry for that! On my disk it was egor32 but somehow git ignored the name change. I guess this is due to Windows ignoring capitalization in file names? Fixed it with separate commits.

I took a look at the examples and am seriously impressed. That is a mighty subsetting function! Especially the combination of alter attributes and alter alter relations is awesome!

**Comment by krivit** [comment]
Thanks! Some bits of UI uncertainty I have is whether we should use 
* `.egoIdx` as a virtual index column and
* `aspect` as the name for the selector for whether the filtering is for egos, alters, or alter-alter ties

or whether better names come to mind.

**Comment by krivit** [comment]
@martinamorris suggested "unit" instead of "aspect".

Another candidate is a verb like "modify" or "filter".

**Comment by tilltnet** [comment]
Hi @martinamorris :)
I was fine with 'aspect' but 'filter' is my favourite.
For the virtual index column: Maybe '.egoIDx'?

**Comment by martinamorris** [comment]
Hi @tilltnet ;)

My only concern with filter is that it usually applies to the variable 
used, and here we have a unit of analysis, as well as a variable.


On Sat, 20 May 2017, tilltnet wrote:

> 
> Hi @martinamorris :)
> I was fine with 'aspect' but 'filter' is my favourite.
> For the virtual index column: Maybe '.egoIDx'?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AH0J4ougztVgEsm0tAH5tbG6uN_XHnsiks5r73gCgaJpZM4NdYix.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by martinamorris** [comment]
not sure this will work, but will give it a try

---------- Forwarded message ----------
Date: Sat, 20 May 2017 16:34:46 -0700 (Pacific Daylight Time)

**Comment by krivit** [comment]
Martina replied in an e-mail, but I tagged her to give her credit.

>  For the virtual index column: Maybe '.egoIDx'?

"Idx" is short for "index", not "identifier". I want to emphasize that this is a number of the current row in the table. That's why it's "virtual": if the table gets subsetted, any "egoIDs" remain the same for the retained egos, but row indices gets renumbered.

**Comment by krivit** [comment]
@martinamorris
The current implementation does these as follows:

```
> subset(nw, unit=ego, attribute(name="sex", value="male"))

subset(egor, sex=="male", aspect="egos")

> subset(nw, unit=alter, term(name="nodematch", attribute="sex")

subset(egor, sex==.alters$sex, aspect="alters")

> subset(nw, unit=altermatrix, term(name="absdiff", attribute="age", value=<5)

subset(egor, abs(.alters$age[.alter_ties$Source] -
             .alters$age[.alter_ties$Target])<=5,
       aspect = "ties")
```

**Comment by krivit** [comment]
On that note, I just realized that the alter-alter code only works because, coincidentally, `alterID`s are numeric row indices. See #7 .

**Comment by martinamorris** [comment]
The first 2 subset syntax rules are good but

>subset(egor, abs(.alters$age[.alter_ties$Source] -
             .alters$age[.alter_ties$Target])<=5,
       aspect = "ties")

this one ... ick.   the complicated syntax is pleading for a utility, and the use of the general word "ties" to refer to alter-alter ties will cause confusion

**Comment by krivit** [comment]
> this one ... ick. the complicated syntax is pleading for a utility, 

It's a complicated operation. The syntax allows for arbitrary interactions between attributes of that ego, all the alters, and the alter-alter ties.

> and the use of the general word "ties" to refer to alter-alter ties will cause confusion

I am aware of that. The reason I didn't use something like "alter-alter" is that it has the same first letter as "alters": right now, you can type

 `subset(egor, sex==.alters$sex, aspect="a")`

and

`subset(egor, abs(.alters$age[.alter_ties$Source] -
.alters$age[.alter_ties$Target])<=5,
aspect = "t")`

and get the same results as the respective expression. Any suggestions?

**Comment by martinamorris** [comment]
> It's a complicated operation. The syntax allows for arbitrary interactions between attributes of that ego, all the alters, and the alter-alter ties.

right, but this kind of syntax will defeat all but your clones.  to me, and your average SNA type, this is not a "difficult" operation conceptually.  so there has to be a way for the syntax to match the simple cognitive task.
 
>The reason I didn't use something like "alter-alter" is that it has the same first letter as "alters"

interesting question.  i wonder if it's worth thinking ahead a bit to multiwave sampling.   we had to adopt a scheme for the Colorado Springs data to identify ties within and between waves.  even if we don't want to consider that now, "w11" might be worth considering, for "wave 1 - wave 1" tie.  or simpler, "wave1", but that doesn't generalize to "w21" in the future.

**Comment by krivit** [comment]
> interesting question. i wonder if it's worth thinking ahead a bit to multiwave sampling. we had to adopt a scheme for the Colorado Springs data to identify ties within and between waves. even if we don't want to consider that now, "w11" might be worth considering, for "wave 1 - wave 1" tie. or simpler, "wave1", but that doesn't generalize to "w21" in the future.

To be clear, by "wave", do you mean it in the snowball/RDS sense, or do you mean multiple observations on some of the egos?

**Comment by tilltnet** [comment]
> right, but this kind of syntax will defeat all but your clones. to me, and your average SNA type, this is not a "difficult" operation conceptually. so there has to be a way for the syntax to match the simple cognitive task.

Pavel's code already simplifies this by a lot. Doing this in base R is much more complicated. With the example in place users can learn from that and adopt it to their needs. And for people familiar with subsetting in R this solution is quite coherent.

Another solution for this is used in igraph. They introduce special comparisons for edge data. Following their pattern the comparisons could look like this:
subset(egor, subset = "m" -- "w", aspect = "ties", alter_var = gender)

'->' and '<-' are used for directed realations in igraph.

> "Idx" is short for "index", not "identifier". 

Alright, I would suggest '.egoIx' or '.ego_ix'. 'ix' is a way a see index abbreviated quite often and it defuses the potential for confusion with eogID.

> I am aware of that. The reason I didn't use something like "alter-alter" is that it has the same first letter as "alters"

I see the convenience in that solution, but a lot of "modern" packages avoid that kind of behaviour as it might be unexpected by the user and instead throw a stop/error when incomplete parameter values are used. On the other hand we need to find solutions for all the var names and terms used in the package that don't add confusion and are in accordance with the literature. I will open a separate Issue for this (#8).

**Comment by martinamorris** [comment]
wave = sampling generations out from ego, same use as RDS or snowball

> Another solution for this is used in igraph. They introduce special comparisons for edge data. 
> Following their pattern the comparisons could look like this:
> subset(egor, subset = "m" -- "w", aspect = "ties", alter_var = gender)

i think our case here is different -- we're not talking about ego-alter ties, but about alter-alter ties.  both may be the target of subsetting, and both have the same features (i.e., node attributes and tie attributes).  

i think the goal is to have a single syntax for attribute filters (nodal or tie related), and then specify which unit you want this filter to operate on.  for nodes the unit choices are ego and alter.  for ties the choices are ego-alter and alter-alter.

**Comment by krivit** [comment]
> wave = sampling generations out from ego, same use as RDS or snowball

One way to represent that is to allow `.alters` tables to have an `$.alters` column, containing its nominations, etc..

**Comment by martinamorris** [comment]
yes, though in this primary case, the alter "nominations" are provided by 
ego.

**Comment by krivit** [comment]
> Alright, I would suggest '.egoIx' or '.ego_ix'. 'ix' is a way I see index abbreviated quite often and it defuses the potential for confusion with eogID.

Now that I think about it, `.egoRow` might be more descriptive. What do you think?

> yes, though in this primary case, the alter "nominations" are provided by ego.

By the second-wave ego?

**Comment by martinamorris** [comment]
>>yes, though in this primary case, the alter "nominations" are provided by ego.
>By the second-wave ego?

no, i mean in a traditional non-link traced egocentric sample, ego reports on the alter-alter ties (for their alters)

**Comment by krivit** [comment]
> no, i mean in a traditional non-link traced egocentric sample, ego reports on the alter-alter ties (for their alters)

Isn't that exactly what `.alter_ties` contains already?

**Comment by tilltnet** [comment]
> Now that I think about it, .egoRow might be more descriptive. What do you think?

.egoRow is good!

As an alternative for 'aspect' I think 'level' would be appropriate, since in the literature and also in the documentation ego/alter/alter-alter data is referred to as data levels. 

In the spirit of simplifying the interface I  suggest introducing a version of the subset Command that uses a 'by' parameter. So the user could specify which level to filter by which level's data. I guess that version wouldn't be as flexible as the original, but it could still do a lot and the conditionals would be less intimidating. If the user doesn't specify a 'by' parameter the regular version would be used. @krivit What do you think about this? Is this sensible?

**Comment by krivit** [comment]
OK, I'll change things over to .egoRow.

I am not sure I understand what you have in mind for a `by` parameter. Can you give an example?

Here are the ideas we have so far for the argument to `subset`:
1. aspect
2. level
3. filter
4. modify
5. unit

Any comments and preferences in this context? I'll poll the UW NMG later today.

**Comment by krivit** [comment]
NMG discussion summary (as I remember it):
* "level" was argued to be confusing, since it's used in other aspects of data analysis (e.g., levels of a factor).
* "frame" was considered to be an alternative, but also confusing, especially in R.
* "filter" had some support.
* "unit" seemed popular among the more senior members of the group.

Myself, I'm leaning toward either "filter" or "unit". "Filter" has the disadvantage that it's unclear whether the argument is the subject or the object of the filtering.

Another option that occurs to me is "target".

**Comment by martinamorris** [comment]
i'd vote for target or unit

**Comment by krivit** [comment]
I'll go ahead with unit. We'll see what the journal reviewers say, if nothing else.

**Comment by krivit** [comment]
@raffaelevacca @tilltnet @martinamorris, I've also added functionality for passing a function rather than an expression (which is more verbose but also more robust). Do any other helpful features come to mind, or can I close this?

**Comment by martinamorris** [comment]
can you give an example of each (function, expression)?

**Comment by krivit** [comment]
@martinamorris, it's all in the help files.

**Comment by krivit** [comment]
Since it looks like `subset.egor()` is more or less complete, I'm closing this. Any further changes might be better discussed by opening new issues.
