### ISSUE TITLE
Example data from GSS 2004

### ISSUE THREAD

**Issue by mbojan** [tilltnet/egor#28]
Not really an issue, but a heads-up. I made a minimal subset  from GSS 2004 data and commit it shortly. I think it will be perfect for illustrations and examples. Also a good testbed for existing and new functions as I put some effort to include most of the quirks GSS data has. :)

**Comment by mbojan** [comment]
FYI, data generating/subsetting code included in `R/gss2004.R`.

**Comment by tilltnet** [comment]
Thanks! This is great!
