### ISSUE TITLE
twofiles_to_egor error message "no rows to aggregate"

### ISSUE THREAD

**Issue by bemezce11412** [tilltnet/egor#29]
Hello, I am relatively new to R and to github, so I apologize if I am misusing the forum.  I attended sunbelt 2019 and was trying to use ego with egocentric data I have.  I formatted the data for twofiles_to_egor to match your example.  In my case, I have egoid, alterid, 18 rows of ego attributes, netsize, and then 54 columns specifying ties ('00.to.01' is a tie from ego to alter 1, '01.to.10' is a tie from alter 1 to alter 10).  I am getting the following errors, which I am unable to troubleshoot: 

> twofiles_to_egor(ego.and.edges, ego.alter.dat, 
+                  netsize = 'netsize',
+                  ID.vars = list(ego = "egoid0", 
+                                 alter = "alterid0"),
+                  e.max.alters = 10,
+                  e.first.var = 21,
+                  ego.vars = evars)
alterID specified; moving to first column of $alters.df.
Sorting data by egoID and alterID.
Preparing alters data.
Error in mapply(FUN = function(x, netsize) x[0:netsize, ], x = tie_list,  : 
  zero-length inputs cannot be mixed with those of non-zero length

and then when not specifying netsize....

> twofiles_to_egor(ego.and.edges, ego.alter.dat, 
+                  #netsize = 'netsize',
+                  ID.vars = list(ego = "egoid0", 
+                                 alter = "alterid0"),
+                  e.max.alters = 10,
+                  e.first.var = 21,
+                  ego.vars = evars)
alterID specified; moving to first column of $alters.df.
Sorting data by egoID and alterID.
No netsize variable specified, calculating/ guessing netsize by egoID in alters data.
Error in aggregate.data.frame(as.data.frame(x), ...) : 
  no rows to aggregate

Many of my alter attributes are dichotomous and some have missing values.  Is that a problem?

Any help would be much appreciated.

Thank you
Ben

**Comment by tilltnet** [comment]
Hi Ben, thanks for filing this issue. Sorry for the late response, I was traveling.

The network size needs to be pointing to a numeric vector. If it is a variable of the "ego.and.edges" dataframe the netsize argument would be specified like this: ego.and.edges$netsize
In case it is a single variable, just drop the quotation marks around it (netsize instead of 'netsize').

If this does not solve your problem, it would be best if you could send some example data, that resembles your original data. If you prefer, you can send me an email at egor@tillt.net

**Comment by bemezce11412** [comment]
Hi Till, I am still having the issue so I sent you some data.  Have you received the email?
Thanks
Ben

**Comment by tilltnet** [comment]
Hi Ben,
I found the bug that caused this. You can either install the development version of egor from github or apply the following workaround to your ego.alter.dat dataframe:

    names(ego.alter.dat)[3] <- "alterID"

Best,
Till

**Comment by bemezce11412** [comment]
Till, than you so much!!!
Ben
