### ISSUE TITLE
egor$ego as tbl_svy objects

### ISSUE THREAD

**Issue by krivit** [tilltnet/egor#32]
As we planned a long time ago, I've implemented it and made the necessary changes for `R CMD check` to run without errors or major warnings. The implementation is in `ego_srvyr` branch.

The trouble I anticipate is that it might be confusing to the users: `alter` and `aaties` are `tibble`s, but `ego` isn't, and, in fact, the `tibble` is in `egor$ego$variables`, and while some accessors, like `egor$ego[,]` work as expected, others like `egor$ego[[]]` don't.

Also, `summarize()` doesn't work as expected. For example, with `ego` active, `summarize(egor, m=mean(a))` for some ego attribute `"a"` won't work, and you'd need to use either `summarize(egor, m=survey_mean(a))` for sample-weighted mean, and `summarize(egor, m=unweighted(mean(a)))` for the unweighted mean.

**Comment by tilltnet** [comment]
Thank you so much! I looked through the commits and it looks like it is on a good way.

As we said in #27, I think it would be good to make the ego object as a  `srvyr` optional.

> Making design optional makes sense. Maybe we can have two subclasses of egor, say, egor_ego_df and egor_ego_svy for those functions that need to handle the two data types differently.

I like this, yes!

**Comment by krivit** [comment]
Changes have been merged.
