### ISSUE TITLE
as_igraph doesn't correctly import .egoID as graph attribute

### ISSUE THREAD

**Issue by raffaelevacca** [tilltnet/egor#51]
`as_igraph(x, graph.attrs = ".egoID")` should return a list of igraphs with each igraph having its egoID (a vector of length 1, from `x$ego$.egoID`) as graph attribute. Instead, the function is setting a one-column tibble with `.egoID` (as in `x$ego[1]`) as graph vector in each igraph. Problem seems to be in `conversions.R`, line 83. Note that `graph.attrs = ".egoID"` is the default in `as_igraph`.

**Comment by tilltnet** [comment]
Thanks for reporting!
