### ISSUE TITLE
Are there resources how to use the package for multilevel modeling available?

### ISSUE THREAD

**Issue by PCK1992** [tilltnet/egor#56]
The package has a lot of great features but I can't quite wrap my head around how to do MLM using the data structure and I couldn't find a reference in the documentation.

```
library(egor)
library(lme4)

data("alters32")
data("egos32")
data("aaties32") 

e1 <- egor(alters = alters32,
           egos = egos32,
           aaties = aaties32,
           ID.vars = list(
             ego = ".EGOID",
             alter = ".ALTID",
             source = ".SRCID",
             target = ".TGTID"))
e1


lmer(income ~  (1|.egoID), data = e1$ego)
```

This doesn't work and I tried different variations of this formula but perhaps a short example of how to get this to work (or how to work with this package for MLM in general) would be highly appreciated!

**Comment by raffaelevacca** [comment]
Hi @PCK1992, below is a reference on multilevel models for ego-networks, and you can contact me via email for the code used in the article's examples (which we've been using for some recent workshops). We're trying to incorporate all this in a vignette as soon as possible.

Vacca, R. (2018). Multilevel models for personal networks: Methods and applications. Statistica Applicata - Italian Journal of Applied Statistics, 1, 59–97. https://doi.org/10.26398/IJAS.0030-003

**Comment by tilltnet** [comment]
This should work for your example.

```
alters_egos <- as_alters_df(e1, include.ego.vars = TRUE)
fitintensity <- lmer(income ~ (1 | .egoID), data = alters_egos) 
```

Currently `egor` does not provide a method for `lme4::lmer()`, but  I can look into adding a method for that.

**Comment by PCK1992** [comment]
Thank you, this is super helpful! I think in my use case it's really the only functionality that I wish was there. Thank you for your quick responses!

**Comment by tilltnet** [comment]
Thank you very much for the feedback @PCK1992 !

My thoughts on adding an `lmer.egor()` and `glmer.egor()` methods:

- There are many ways researchers apply MLM to ego-centered network data. I think most commonly alter level variables are regressed on an ego characteristic.
-  Creating an interface that accommodates for the diversity of possible model types might be hard.
- The methods could cover the most common case(s) and the vignette @raffaelevacca  mentioned above would demonstrate how to accomplish more complex model designs.

**Comment by PCK1992** [comment]
That's true, especially if you want to interface it with any package outside of `lme4`. I think a vignette should be enough for the most common use cases and this could be then easily extended to other packages (e.g. `brms`, etc.).
