### ISSUE TITLE
Renaming Functions (change dots to underscores)

### ISSUE THREAD

**Issue by tilltnet** [tilltnet/egor#6]
I suggest renaming some import functions and **maybe** rename all functions that are no S3 methods to using underscores instead of dots(?).

For the import functions I suggest:

- read.egonet.folders -> read_egonet
- read.egoweb -> read_egoweb
- read.openeddi -> read_openeddi

The following import functions don't read from disk, hence their current names are confusing.

- read.egonet.one.file -> onefile_to_egor
- read.egonet.two.files -> twofiles_to_egor
- read.egonet.three.files -> threefiles_to_egor

**Comment by krivit** [comment]
I'm fine with this.

**Comment by tilltnet** [comment]
Most of the exported functions are changed to the underscore naming scheme. @krivit Since I thought you might have local changes to alter.desgin and ego.design waiting I didn't update there, let me know if I am can change those too.

Notes: 

- generate.sample.ego.data() still needs to be changed as well (Any suggestions for a more elegant name?)
- to.network is obsolete and will be deleted (to_network and to_igraph supersede to.network)

**Comment by krivit** [comment]
Why not `as.network` and `as.igraph` for consistency with the other `as.*` functions?

**Comment by mbojan** [comment]
I'm with @krivit on that. Why not methods for existing generics: `igraph::as.igraph`, `network::as.network`?

**Comment by mbojan** [comment]
While you are on that, do note that we already have `ergm.ego::as.network.egor`. However, it does something rather specific. Perhaps the `as.network.egor` method should just transform the **data** to a  network object having nodes for both egos and alters and all the node attributes? Additionally it might add a logical node attribute like `.is_ego` that marks which nodes are egos?

This is related to my more general observation about the current `egor` implementation: it is cumbersome to process variables that are common to egos and alters (say, age) in one go. I'll drop a separate issue on that.

**Comment by krivit** [comment]
@mbojan, how would the egos + alters network be used in practice?

**Comment by mbojan** [comment]
Well, for example:

- Working with attributes in a joint way: 
    - Using `network` facilities: `net %v% "agegroups" <- cut(net %v% age, breaks=4)` etc.
    - Using `tidygraph` directly
- Some of the descriptives will not require dedicated implementation, like `mixingmatrix()`

Unless multiple people report on the same piece of reality (e.g. two egos reporting on the same alter), IMHO this is a useful data format to have.

I don't want to hijack this issue. I'll drop a new one with some more examples, I will be curious in your opinions then.

**Comment by tilltnet** [comment]
@mbojan thanks for your input! I created a new Issue for this discussion #12

**Comment by tilltnet** [comment]
All functions are renamed now.

Concerning the conversion function to network and igraph objects, I went with as_network and as_igraph, instead of methods for the dot-variants (as.network, as.igraph), since the return value of these functions differ from the output generated by egor's conversions (list of objects vs. objects). This way the documentation is more transparent and explicit about the returned values.
