### ISSUE TITLE
Should we rename `as.egor` to `as_egor`?

### ISSUE THREAD

**Issue by tilltnet** [tilltnet/egor#60]
#57 made be aware of the inconsistency of having `as.egor()` while all other similar functions are `as_*`. Are there any objections to renaming `as.egor()` to `as_egor()`?

**Comment by krivit** [comment]
Well, the base R convention is `as.`, but Tidyverse is all about `as_`, so I can see the case either way.

**Comment by tilltnet** [comment]
Revisiting this I do now think we should stick with the dot for the `as*()` functions.
