### ISSUE TITLE
Next release should be version number 1.x

### ISSUE THREAD

**Issue by tilltnet** [tilltnet/egor#61]
My understanding is that re-submitted packages that run through all the CRAN checks without warnings and notes are automatically processed and uploaded to CRAN, without the need of a human reviewing the submission.

The current version number starts with a zero, which creates a note in the check logs. 

I think we should consider switching to 1.21.x for the next release in order to create less work for CRAN maintainers and have egor updates on CRAN quicker.

The list of features and the stability of the `egor` do also justify leaving beta territories, I think.

**Comment by mbojan** [comment]
What's the versioning scheme? Why not 1.0.0? I'm a fan of https://semver.org/ i.e. advance major if making backward-incompatbile changes but moving out of beta is quite an occasion ;)

**Comment by tilltnet** [comment]
The version scheme is: ~major.year.month 
Inspired by what Ubuntu does. I like that I know how old the version is, just by looking at the version number.
If there is more than one release in a month, the second one would be 1.21.03b and so on.

**Comment by tilltnet** [comment]
Maybe 1.21.03.1 would be more consistent for a second release in the same month.
