### ISSUE TITLE
ego-socio-gram do not seem to corelate the information of my egor object

### ISSUE THREAD

**Issue by Josefauwu** [tilltnet/egor#62]
Hi! 

When using the shiny app or the plot function for an "ego-socio-gram", the information selected for pie and venn variables does not correspond with the plot. 

I have three variables for all my alter-data. In each of these variables assigned to my alters, there are three categories / attributes. 
When using shiny app, in the vertices tab, it correctly recognizes the information to be able to assign size, color, labels, etc. 
However, when using > plot options > venn variable or pie variable, the vertices do not correspond with the information I assign (neither with the pie sector, nor with the venn variable). 

I already ruled out that there is a failure of my database (I am working with very little data, so there is no problem there). Somehow, the program is not assigning correctly the values of my data with what I ask it in the pie and venn variables. I tried with the plot function, and the result remains pretty much the same. 

I add a picture of my problems with the pie variables:
- all the "Estado" ones, should be in the "state" section (pie portion white).
- all "Sociedad Civil" ones -> pie portion light blue ("Civil Society")
- all "Privados" -> pie portion pink ("Privados"). 

Idem with my venn variables:
- the red balls should be in the radius 3
- the orange balls should be in the radius 2
- the yellow ones should be in the radius 1.
 
help!

![enviar xd](https://user-images.githubusercontent.com/79614730/109091505-af977000-76f3-11eb-912d-6f089a510003.PNG)

**Comment by tilltnet** [comment]
Hi,
thanks for posting! You closed the issue, I assume you found a solution? 
Would you mind to share what the issue was?
Thanks!

**Comment by Josefauwu** [comment]
Dear Till, 

I was actually playing around with make_egor, to make sure there was a problem associated with the package execution. However, I have not been able to solve my problem when plotting my venn vars and pie vars in order to group my actors according to the corresponding type. 

plot_egograms(x = make_egor(3,18),
              ego_no = 2,
              venn_var = "sex",
              pie_var = "country",
              vertex_size_var = "age")

(the election of 3 and 18 is randomly decided). 

I used make_egor and indeed, the data is grouped according to the "portion" of the pie. I don't think it's a problem with my database, but I recognize that it must be a problem associated with my poor handling with the package :'( 

plot_egograms(x = e1,
              ego_no = 1,
              venn_var = "Nivel.de.Involucramiento",
              pie_var = "Sector",
              vertex_color_var = "Nivel.de.Involucramiento",
              vertex_label_var = "Sector”)

(e1 is associated to the way I organized my database)

If u can give some insight or direction on this, I will be very thankful. Of course, I know I should socialize this in here :)

**Comment by tilltnet** [comment]
Is it possible for you to share your data with me? A subset of the data with just one ego and the relevant variables would suffice. You can send me an email at egor@tillt.net with the data.

**Comment by tilltnet** [comment]
I think I have found the issue and I will work on a fix soon.

In the meantime please try this as a workaround:

e1 %>%
  acticate(alter) %>%
  arrange(.egoID, .altID) %>%
  plot_egograms(
    x = e1,
    ego_no = 1,
    venn_var = "Nivel.de.Involucramiento",
    pie_var = "Sector",
    vertex_color_var = "Nivel.de.Involucramiento",
    vertex_label_var = "Sector”)

**Comment by Josefauwu** [comment]
Somehow, it was necessary to order the variables somehow in advance, in order to get the nodes according to their belonging to the pie var. 

This was my solution:

library(tidyverse)
library(egor)
 
# tranforming chr to factores.
alters <- f_chr_to_factor(alters)
# Names for vertex
alters <- mutate(alters, 
                 label = as.character(.ALTID))

aaties %>% as_tibble() %>% head()

aaties <- aaties %>% 
  mutate(.EGOID = factor(.EGOID,
                         labels = levels(alters$.EGOID)),
         .SRCID = factor(.SRCID,
                         labels = levels(alters$.ALTID)),
         .TGTID = factor(.TGTID,
                         labels = levels(alters$.ALTID))) %>% 
  as_tibble()

levels(aaties$.SRCID)
levels(alters$.ALTID)

ego <- ego %>% 
  mutate(.EGOID = factor(.EGOID,
                         labels = levels(alters$.EGOID))) %>% 
  as_tibble()

e1 <- egor (alters = alters,
            egos = ego,
            aaties = aaties,
            ID.vars = list(
              ego = ".EGOID",
              alter = ".ALTID",
              source = ".SRCID",
              target = ".TGTID"))

plot_egograms(e1,
              x_dim = 1, y_dim = 1,
              venn_var = 'Nivel.de.Involucramiento',
              pie_var = 'Sector',
              edge_color_var = 'color',
              edge_color_palette = 'Blue-Red',
              vertex_size_var = 'Menciones',
              vertex_label_var = 'label',
              ... = list(
                label.family = 'Courier',
                label.font = 'Courier',
                frame.color = 'red'))
e1

egor_vis_app(e1)
