### ISSUE TITLE
Plot egograms: Setting manually colors and fonts 

### ISSUE THREAD

**Issue by Josefauwu** [tilltnet/egor#65]
I'm experiencing trouble in setting manually other colors for nodes, edge, fonts and backgrounds in the egograms. 
Is there any possibility to modify this palette? (or as it can be seen in the examples for the shiny app)

This would be ideal, especially for the egogram in the background and the associated default colors (baby blue, pink, light yellow).

**Comment by tilltnet** [comment]
You can use the `venn_colors` argument for this. It can be a vector of
color names as defined in `colors()`...

``` r
library(egor)
e1 <- make_egor(32, 16)


plot(
  e1,
  venn_var = "sex",
  pie_var = "country",
  type = "egogram",
  venn_colors = c("white", "blue")
)
```

![](https://i.imgur.com/ETyOcVw.png)

... or hex code color definitions (a mixture of both also works!).

``` r
plot(
  e1,
  venn_var = "sex",
  pie_var = "country",
  type = "egogram",
  venn_colors = c("#eeffee", "#ff0000", "#aefaef", "#aaaaaa")
)
```

![](https://i.imgur.com/WR6MfhT.png)
