### ISSUE TITLE
Error when attempting to plot ego and ego-alter ties

### ISSUE THREAD

**Issue by gabevar** [tilltnet/egor#66]
Hi,

Apologies for potential naive question. When attempting to use "include_ego = T", I get the following error:

> Error in if (lambda[i] == 0) { : missing value where TRUE/FALSE needed

The traceback tracks the error down to this function:

> igraph.Arrows(x0, y0, x1, y1, h.col = edge.color, sh.col = edge.color, sh.lwd = edge.width, h.lwd = 1, open = FALSE, code = arrow.mode[1], sh.lty = edge.lty, h.lty = 1, size = arrow.size, width = arrow.width, curved = curved)

Here is code that reproduces the error for me

`e <- make_egor(net.count = 5, max.alters = 12)`

`plot_egograms(x = e, 
        ego_no = 2, 
        venn_var = "sex", 
        pie_var = "country", 
        vertex_size_var = "age", 
        include_ego = T)`

Let me know if I can give you more info or help.

And thank you for the amazing package !

**Comment by tilltnet** [comment]
Hi, I have looked into this and with the next update `plot_egograms()` with `include_ego = TRUE` will work. We are planning to submit a new version to CRAN by/on June 9th.
