### ISSUE TITLE
Standardize alter ID name

### ISSUE THREAD

**Issue by krivit** [tilltnet/egor#7]
When alter-alter ties are not observed, this is irrelevant. When they are observed, there needs to be a way to link the alters to alter-alter ties. I see two solutions:

1. Positionally: an `.alter_ties` for an ego becomes an actual matrix of mode `list` (i.e., each cell is a `list`), which contains the attributes of that particular tie (or NULL if no tie). This is arguably the most elegant solution, but it would require rewriting a lot of things.
2. Relationally: `.alters` has a well-identified column of values unique to each ego, and `.alter_ties` has a column for tail and head of that tie. This is the current solution.

If we stay with 2, we should probably add another `attr` to the `egor` object, say, `alterID` (which might also be a part of the `alter.design` list), which tells `egor` which alters to link to which alter-alter ties.

**Comment by krivit** [comment]
Actually,

3. No well-identified column: the order of the alters in the dataset is the order of the ties. We reserve a column in`.alter_ties` e.g., `.alter1` and `.alter2`, and store the tail and the head ID there, identified by rows. Then, any slicing and permutation of alters will need to be accompanied by renumbering of `.alter1` and `.alter2`.

**Comment by krivit** [comment]
I am increasingly liking Option 3.

**Comment by krivit** [comment]
@tilltnet, @raffaelevacca, what do you think?

**Comment by tilltnet** [comment]
I am used to 2. and therefore prefer it very much. 1. sounds interesting but since there is no print method for matrix of mode list, that is as humanly readable as the print method of a dataframe (or is there?), I don't think it is suitable for egor. The user should be able to comfortably check the data in the egor object with their source material. Having a dataframe  serving as an edge list is nice for that.

I would argue in a similar manner in regard to 3. When changing the values of 'head' and 'tail' from alterIDs to rownames of .alters, that would be confusing to the users and they might lose confidence in their data's integrity. If we go with this solution the original columns with the alterIDs should be kept. Than again, that would introduce redundancy which might me another source for confusion. I'm skeptical about 3.

Can we make sure the subsetting of alter_ties by alter attributes works with 2. somehow?

(Currently I don't have the time and peace to implement a solution, but I could spend some time on this in a few days.)

**Comment by krivit** [comment]
The advantage of 3 is that it makes "joining" alters to alter-alter ties very easy, as in `subset.egor` example:
```
subset(egor, abs(.alters$age[.alter_ties$Source] -
             .alters$age[.alter_ties$Target])<=5,
       aspect = "ties")
```
This only works because `Source` and `Target` refer to actual rows of `.alters`. A version with a separate `alterID` would require something like 
```
subset(egor, abs(.alters$age[.alter_ties$Source==.alters$alterID] -
             .alters$age[.alter_ties$Target==.alters$alterID])<=5,
       aspect = "ties")
```
I agree that we should keep egoID and alterID rows, but I think that they shouldn't be integral to the data structure. (egoID is already unnecessary, since egos already "contain" the alters.)

Another option is to use some trick like with `.egoIdx` to have columns `.src` and `.tgt` (or `.a1` and `.a2` for a more concise and neutral naming) that would always be `Source` and `Target` mapped onto row number, so the above becomes 
```
subset(egor, abs(.alters$age[.alter_ties$.src] -
             .alters$age[.alter_ties$.tgt])<=5,
       aspect = "ties")
```
we'd need to see how big a speed hit this would entail.

**Comment by tilltnet** [comment]
> I agree that we should keep egoID and alterID rows, but I think that they shouldn't be integral to the data structure. (egoID is already unnecessary, since egos already "contain" the alters.)
> 
> Another option is to use some trick like with .egoIdx to have columns .src and .tgt (or .a1 and .a2 for a more concise and neutral naming) that would always be Source and Target mapped onto row number, so the above becomes
> 
> subset(egor, abs(.alters$age[.alter_ties$.src] -
>              .alters$age[.alter_ties$.tgt])<=5,
>        aspect = "ties")
> 
> we'd need to see how big a speed hit this would entail.

I would prefer this solution then! I will get up to speed with your subset code in the next days and should then be able to help with this one.

**Comment by krivit** [comment]
@tilltnet, I can do the implementation myself; what I need, though, is a standard way to identify *which* column in `.alters` is the alterID.

I see three possibilities:
1. `attr(egor, "alterIDcol")` or similar name.
2. `alter.design(egor)$alterIDcol` (i.e., in the alter design information list).
3. Fixed standard column name (`.alterID`).

All three could have fallback to positional indexing if alter ID column name is `NULL`.

Any preferences?

**Comment by tilltnet** [comment]
I think 2. is my favorite here, since it makes use of the exisiting structure. But, if there are downsides to the second option, going with 3. would be alright as well.

**Comment by krivit** [comment]
3 would probably make the importing code a little more complicated, but it would simplify other code. Compare:

Variable alterID:
```
subset(egor, abs(.alters$age[match(.alter_ties$Source, .alters[[alter.design(egor)$alterIDcol]])] -
             .alters$age[match(.alter_ties$Target, .alters[[alter.design(egor)$alterIDcol]])])<=5,
       aspect = "ties")
```
versus

```
subset(egor, abs(.alters$age[match(.alter_ties$Source, .alters$.alterID)] -
             .alters$age[match(.alter_ties$Target, .alters$.alterID)])<=5,
       aspect = "ties")
```
Also, in the spirit of keeping keystrokes to a minimum, perhaps use just `.alter` instead of `.alterID`?

That said, if we implement the idea of row-based "shortcuts", the whole `match()` construction will be unnecessary.

**Comment by krivit** [comment]
I think that that resolves that.
