### ISSUE TITLE
Mismatch in argument names for `ID.vars` and `ego_design` arguments

### ISSUE THREAD

**Issue by Tom-Wolff** [tilltnet/egor#85]
Sorry for the delay— following up on an earlier issue I identified some time before. If I recall correctly, `egor` processes/renames the strings used for `ID.vars` arguments such that, in some cases, they no longer match those strings when used as arguments in `ego_design`. Capitalization of items in strings was the main source of the issue from what I recall. For the moment, the most effective workaround is to ensure one's ego, etc. variables are named `.egoID`, `.altID`, and so on, as those variables are named in `egor`'s documentation and vignettes.

**Comment by mbojan** [comment]
Hello @Tom-Wolff do you mean issue #73 which was about improving documentation?

**Comment by Tom-Wolff** [comment]
Yes!

**Comment by mbojan** [comment]
OK. Would you mind re-posting your comment at #73 and I'm closing this issue.
