### ISSUE TITLE
ego_design argument of egor is not lazy-evaluated

### ISSUE THREAD

**Issue by mbojan** [tilltnet/egor#90]
At this moment we write in the docs of `egor()` that

> `ego_design`	A [list](http://127.0.0.1:20143/help/library/egor/help/list) of arguments to [srvyr::as_survey_design()](http://127.0.0.1:20143/help/library/srvyr/help/as_survey_design) specifying the sampling design for the egos. If formulas, they can refer to columns of egos.df. NULL means that no design is set.
>
> `alter_design` A [list](http://127.0.0.1:20143/help/library/egor/help/list) of arguments specifying nomination information. Currently, the following elements are supported (...)

while arguments `srvyr::as_survey_design()` are in fact lazy-evaluated so e.g. accept unquoted variable names. For example for `weights`:

``` r
library(egor)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Loading required package: tibble

a <- tribble(
  ~egoID, ~alterID,
  1, 1,
  1, 2,
  2, 1,
  2, 2
)

e <- tribble(
  ~egoID, ~ w,
  1, 1,
  2, 2
)


d1 <- srvyr::as_survey_design(e, weights = w) # lazy eval works
d2 <- srvyr::as_survey_design(e, weights = "w") # works too
identical(d1, d2)
#> [1] TRUE

# Works
egor(
  alters = a,
  egos = e,
  ego_design = list(weights = "w")
)
#> # EGO data with survey design (active): 2 × 2
#>   .egoID     w
#> * <chr>  <dbl>
#> 1 1          1
#> 2 2          2
#> # ALTER data: 4 × 2
#>   .altID .egoID
#> * <chr>  <chr> 
#> 1 1      1     
#> 2 2      1     
#> 3 1      2     
#> # ℹ 1 more row
#> # AATIE data: 0 × 3
#> # ℹ 3 variables: .egoID <chr>, .srcID <chr>, .tgtID <chr>

# Not
egor(
  alters = a,
  egos = e,
  ego_design = list(weights = w)
)
#> Error in eval(expr, envir, enclos): object 'w' not found

# Not work because expecting column name, not a vector of weights
wei <- e$w  
egor(
  alters = a,
  egos = e,
  ego_design = list(weights = wei)
)
#> Error in 1/as.matrix(weights): non-numeric argument to binary operator
```

I guess for now we can get away with more precise docs. In the long run we should probably pass it rlang-style...

**Comment by tilltnet** [comment]
After looking into this for a bit I think the simple  solution is to add the `as_survey_design()` arguments to `egor()`.

I thought this could be solved with `rlang::enquos()` and the splice operator `!!!`. after studying the `rlang` docs on the topic it seems like it won't work because `as_survey_design()` does not have a dynamic dots argument (not sure if that is the only hurdle). 

@mbojan or @krivit do you have any other ideas?

**Comment by krivit** [comment]
One quick workaround is to tell the users to use `alist()` instead of `list()`. `alist()` (short for argument list) stores its arguments as names or calls and doesn't evaluate them:

``` r
suppressPackageStartupMessages(library(egor))

a <- tribble(
  ~egoID, ~alterID,
  1, 1,
  1, 2,
  2, 1,
  2, 2
)

e <- tribble(
  ~egoID, ~ w,
  1, 1,
  2, 2
)

char <- egor(
  alters = a,
  egos = e,
  ego_design = list(weights = "w")
)

lazy <- egor(
  alters = a,
  egos = e,
  ego_design = alist(weights = w)
)

identical(char, lazy)
#> [1] TRUE
```
<sup>Created on 2024-09-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

We can patch the code to try to produce an informative error message.

**Comment by krivit** [comment]
It even works with tidyselect:
``` r
suppressPackageStartupMessages(library(egor))

a <- tribble(
  ~egoID, ~alterID,
  1, 1,
  1, 2,
  2, 1,
  2, 2
)

e <- tribble(
  ~egoID, ~ w, ~v, ~z,
  1, 1, 3, 5,
  2, 2, 4, 6
)

char <- egor(
  alters = a,
  egos = e,
  ego_design = list(weights = c("w","v","z"))
)

char$ego
#> Independent Sampling design (with replacement)
#> Called via srvyr
#> Sampling variables:
#>   - ids: `1` 
#>   - weights: `w + v + z` 
#> Data variables: 
#>   - .egoID (chr), w (dbl), v (dbl), z (dbl)


lazy <- egor(
  alters = a,
  egos = e,
  ego_design = alist(weights = w:z)
)

lazy$ego
#> Independent Sampling design (with replacement)
#> Called via srvyr
#> Sampling variables:
#>   - ids: `1` 
#>   - weights: `w + v + z` 
#> Data variables: 
#>   - .egoID (chr), w (dbl), v (dbl), z (dbl)

identical(char, lazy)
#> [1] TRUE
```

<sup>Created on 2024-09-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by krivit** [comment]
So what do we want to do here? Update docs to tell people to use `alist()` and add an informative error message?
